kind: pipeline
type: docker
name: deploy-octocord-api

steps:
  - name: build-and-push
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: '1'
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: icarocedraz/octocord-api
      tags: latest
      cache_from: icarocedraz/octocord-api:latest

  - name: deploy-to-server
    image: bitnami/kubectl:latest
    environment:
      KUBECONFIG: /root/.kube/config
    volumes:
      - name: kubeconfig
        path: /root/.kube
    commands:
      - kubectl rollout restart deployment/octocord-api

  - name: notificar-falha-discord
    image: appleboy/drone-discord
    settings:
      webhook_url:
        from_secret: discord_webhook
      message: '🚨 Falha no pipeline do repositório **${DRONE_REPO}** na branch **${DRONE_BRANCH}**.'
    when:
      status:
        - failure

volumes:
  - name: kubeconfig
    host:
      path: /home/cedraz-ubuntu-2/.kube

trigger:
  branch:
    - main
  event:
    - push
