kind: pipeline
type: docker
name: deploy-octochord-api

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: icarocedraz/octochord-api
      tags: latest
      cache_from: icarocedraz/octochord-api:latest
      cache_to: icarocedraz/octochord-api:latest,mode=max

  - name: deploy-to-server
    image: docker:23
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: project-files
        path: /app
    commands:
      - apk add --no-cache docker-cli-compose
      - cd /app
      - docker compose -p octochord --env-file .env.prod pull
      - docker compose -p octochord --env-file .env.prod down --remove-orphans || true
      - docker compose -p octochord --env-file .env.prod up -d --force-recreate --remove-orphans

  - name: notificar-falha-discord
    image: appleboy/drone-discord
    settings:
      webhook_url:
        from_secret: discord_webhook
      message: '🚨 Falha no pipeline do repositório **${DRONE_REPO}** na branch **${DRONE_BRANCH}**.'
    when:
      status:
        - failure

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: project-files
    host:
      path: /home/cedraz-ubuntu-2/Documentos/deploys/octochord

trigger:
  branch:
    - main
  event:
    - push
