kind: pipeline
type: docker
name: deploy-octochord-api

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: icarocedraz/octochord-api
      tags: latest
      cache_from: icarocedraz/octochord-api:latest
      build_args:
        - DOCKER_BUILDKIT=1

  - name: deploy-to-server
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      script:
        - export KUBECONFIG=/home/cedraz-ubuntu-2/.kube/config
        - kubectl rollout restart deployment/octochord-api

  - name: notificar-falha-discord
    image: appleboy/drone-discord
    settings:
      webhook_url:
        from_secret: discord_webhook
      message: '🚨 Falha no pipeline do repositório **${DRONE_REPO}** na branch **${DRONE_BRANCH}**.'
    when:
      status:
        - failure

trigger:
  branch:
    - main
  event:
    - push
