services:
  api-octochord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-octochord
    ports:
      - 3000:3000
    env_file:
      - .env.prod
  
  postgres-octochord:
    image: postgres:15-alpine
    container_name: postgres-octochord
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env.prod
    volumes:
      - pgdata-octochord:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  redis:
    image: redis:7-alpine
    container_name: redis-octochord
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - octochord-redis-data:/data
    env_file:
      - .env.prod
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

volumes:
  api-octochord-data:
  octochord-redis-data:
  pgdata-octochord:

