services:
  api-octocord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-octocord
    ports:
      - 3000:3000
    env_file:
      - .env.prod
  
  postgres-octocord:
    image: postgres:15-alpine
    container_name: postgres-octocord
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env.prod
    volumes:
      - pgdata-octocord:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  redis:
    image: redis:7-alpine
    container_name: redis-octocord
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - octocord-redis-data:/data
    env_file:
      - .env.prod
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

volumes:
  api-octocord-data:
  octocord-redis-data:
  pgdata-octocord:

