export const QueueNames = {
  INGEST_EVENT_QUEUE: 'INGEST_EVENT_QUEUE',
  SEND_EMAIL_QUEUE: 'SEND_EMAIL_QUEUE',
  CLEAR_ONE_TIME_CODES_QUEUE: 'CLEAR_ONE_TIME_CODES_QUEUE',
  API_HEALTH_CHECK_QUEUE: 'API_HEALTH_CHECK_QUEUE',
};
