export const QueueNames = {
  INGEST_EVENT_QUEUE: 'INGEST_EVENT_QUEUE',
  SEND_EMAIL_QUEUE: 'SEND_EMAIL_QUEUE',
  API_HEALTH_CHECK_QUEUE: 'API_HEALTH_CHECK_QUEUE',
  SEND_DISCORD_MESSAGE_QUEUE: 'SEND_DISCORD_MESSAGE_QUEUE',
};
